### Create a new order
POST http://localhost:8222/api/v1/orders
Content-Type: application/json

{
  "id": null,
  "reference": "ORD-2025-002",
  "amount": 109.24,
  "paymentMethod": "PAYPAL",
  "customerId": "6777ef0c2ffe51723602f08b",
  "products": [
    {
      "productId": "978cd623-7d6f-4233-a9e5-8132b657f127",
      "quantity": 2
    },
    {
      "productId": "a6d29e59-2f3e-4239-bbad-bc43065ceab2",
      "quantity": 1
    }
  ]
}

### fetch orders
GET localhost:8222/api/v1/orders
