spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        # the consumer specify to the producer the object that is sent and where it is coming from
        spring.json.type.mapping: orderConfirmation:de.bertin.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:de.bertin.ecommerce.kafka.payment.PaymentConfirmation
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8094